# OpenShift / RHEL build using OCP builder and base images.
# Build from repo root, e.g.:
#   podman build -f Dockerfile.openshift -t dra-driver-sriov:openshift .

FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder
WORKDIR /go/src/github.com/k8snetworkplumbingwg/dra-driver-sriov
COPY . .

# OpenShift golang builders set GOFLAGS=-mod=vendor; this repo does not vendor deps (lack of vendor directory).
ENV GOFLAGS="-mod=mod"

RUN mkdir /artifacts
RUN make PREFIX=/artifacts cmds

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9

LABEL io.k8s.display-name="Dynamic Resource Allocation (DRA) resource driver for SR-IOV devices" \
      io.k8s.description="This is a component of OpenShift Container Platform that provides a DRA resource driver for SR-IOV devices." \
      io.openshift.tags="openshift,networking,sriov,dra" \
      name="Dynamic Resource Allocation (DRA) resource driver for SR-IOV devices" \
      maintainer="Multus team <multus-dev@redhat.com>"

ENV INSTALL_PKGS="hwdata pciutils"
RUN yum -y update && \
    yum install -y ${INSTALL_PKGS} && \
    rpm -V ${INSTALL_PKGS} && \
    yum clean all

COPY --from=builder /artifacts/dra-driver-sriov /usr/bin/dra-driver-sriov
